# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ymEFeWomhThPDVq7aQ4izd5_LYQJSavl
"""

from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import joblib

iris = load_iris()
X, y = iris.data, iris.target

model = RandomForestClassifier()
model.fit(X, y)

joblib.dump(model, 'iris_model.pkl')
print("Model saved as iris_model.pkl")

# app.py

from flask import Flask, render_template, request
import joblib
import numpy as np

# initialize flask app
app = Flask(__name__)

# Load trained model
model = joblib.load('iris_model.pkl')

@app.route('/')
def home():
    return render_template('home.html')

@app.route('/predict', methods=['POST'])
def predict():

    #get data from form
    try:
        features = [float(request.form[f'feature{i}']) for i in range(1, 5)]
    except ValueError:
        return render_template('result.html', prediction='Invalid input. Please enter numeric values.')

    # Make prediction
    prediction = model.predict([features])[0]

